// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7VautwglE6X6jIRs0FmiASqPmftd96Sc',
    appId: '1:31323305122:web:33f0ebaf46feb92d1513fb',
    messagingSenderId: '31323305122',
    projectId: 'team-project-mds',
    authDomain: 'team-project-mds.firebaseapp.com',
    storageBucket: 'team-project-mds.firebasestorage.app',
    measurementId: 'G-XSKX5JLF78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNnBaf5-Yb_e7_d-ygx4IGAoylN9-0OvE',
    appId: '1:31323305122:android:c6946ac50c3993a41513fb',
    messagingSenderId: '31323305122',
    projectId: 'team-project-mds',
    storageBucket: 'team-project-mds.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiLAbVHGZhEFqQuNTVLToY6W_4td3gQgM',
    appId: '1:31323305122:ios:a8c90f85e83f7abf1513fb',
    messagingSenderId: '31323305122',
    projectId: 'team-project-mds',
    storageBucket: 'team-project-mds.firebasestorage.app',
    iosBundleId: 'com.antigravity.edutiktok.eduTiktokApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiLAbVHGZhEFqQuNTVLToY6W_4td3gQgM',
    appId: '1:31323305122:ios:a8c90f85e83f7abf1513fb',
    messagingSenderId: '31323305122',
    projectId: 'team-project-mds',
    storageBucket: 'team-project-mds.firebasestorage.app',
    iosBundleId: 'com.antigravity.edutiktok.eduTiktokApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7VautwglE6X6jIRs0FmiASqPmftd96Sc',
    appId: '1:31323305122:web:22c74885d8f2d1631513fb',
    messagingSenderId: '31323305122',
    projectId: 'team-project-mds',
    authDomain: 'team-project-mds.firebaseapp.com',
    storageBucket: 'team-project-mds.firebasestorage.app',
    measurementId: 'G-H2TCJ6NCXE',
  );
}
